### ISSUE TITLE
please don't use steemd-int.steemit.com

### ISSUE THREAD

**Issue by sneak** [jamzed/steemit-php#1]
https://github.com/jamzed/steemit-php/blob/e9baacda5c704725c1e7401808c547e44b49a6fd/src/Api/Request.php#L17

Please use only https://api.steemit.com.  steemd-int is, well, int.

**Comment by jamzed** [comment]
Hey @sneak, thank you, let me remove all staging hosts from the code just in case.
 
BTW I'm not using this library and probably nobody else too, I switched to steem-python and hit api.steemit.com ;-)

**Comment by jamzed** [comment]
Done.
